# Generated by Django 5.0.1 on 2024-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('clue1', models.IntegerField()),
                ('clue2', models.IntegerField()),
                ('clue3', models.IntegerField()),
                ('password', models.CharField(default='password', max_length=100)),
                ('time_taken', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
