# Generated by Django 5.0.1 on 2024-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='rollno',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
