# Generated by Django 5.0.1 on 2024-02-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
