# Generated by Django 5.0.1 on 2024-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_players_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
