# Generated by Django 5.0.1 on 2024-02-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_players_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
