# Generated by Django 5.0.1 on 2024-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_players_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='rollno',
            field=models.CharField(max_length=100),
        ),
    ]
